Skip write to 'name' property if not [[writable]]
sinonjs/sinon pull request #2304
Opened 2020-10-18 20:08 UTC by sjoseph7

#### Purpose (TL;DR) - mandatory

Fix issue #2203 by skipping 'name' property if it is not [[writable]].

 #### How to verify - mandatory
1. Check out this branch
2. `npm install`
3. `npm test`

 #### Checklist for author

- [X] `npm run lint` passes // unable to run npm script on Windows, linted manually with `eslint --fix`.
- [X] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

2020-10-27 17:55 UTC, mroderick requested changes
Thank you for your pull request to fix this issue 💯 

I have a couple of stylistic suggestions, trying out the multiline suggestions feature in the process.

2020-10-27 17:55 UTC, mroderick commented on lib/sinon/util/core/extend.js
> +        }
The  comment explains the idea, the implementation uses inversed logic, making it difficult to follow.

Instead, I suggest dropping the comment and make the implementation say what the comment said:

```suggestion
        if (prop === "name" && !destOwnPropertyDescriptor.writable) {
        	return;
        }

        Object.defineProperty(dest, prop, {
            configurable: sourceOwnPropertyDescriptor.configurable,
            enumerable: sourceOwnPropertyDescriptor.enumerable,
            writable: sourceOwnPropertyDescriptor.writable,
            value: sourceOwnPropertyDescriptor.value
        });
```

2020-10-27 17:55 UTC, mroderick commented on test/extend-test.js
> +    });
Mocha's [`context` keyword in the BDD interface](https://mochajs.org/#bdd) is a convenient way of organising code. It allows us to only specify the expectation in the `it` block.

```suggestion
    context("when 'name' property is not writable", function(){
        it("does not attempt to write to the property", function() {
            var object1 = { prop1: null };

            Object.defineProperty(object1, "name", {
                configurable: false,
                enumerable: true,
                value: "not-writable",
                writable: false
            });

            var object2 = {
                prop2: "hey",
                name: "write-attempt"
            };

            var result = extend(object1, object2);

            var expected = {
                prop1: null,
                prop2: "hey",
                name: "not-writable"
            };

            assert.equals(result, expected);
        });
    });
```

2020-10-27 22:21 UTC, sjoseph7 reviewed
I've committed the changes - thanks for the feedback 👍🏾

2020-10-27 22:47 UTC, sjoseph7 reviewed
~ Linted ~

2020-10-28 08:53 UTC, merged

2020-10-28 09:01 UTC, mroderick commented
This has been published with `sinon@9.2.1`