Make sandbox concurrency safe
sinonjs/sinon pull request #2575
Opened 2024-01-04 17:38 UTC by remorses

#### Make sandbox concurrency safe

Fix #2472, sandbox not working when running tests concurrently because of global callId variable

 #### Solution

Store callId in a context passed with an optional argument, which is the sandbox object when using sandbox

#### How to verify - mandatory

Added a test with the #2472 reproduction

1. Check out this branch
2. `npm install`
3. npm test

#### Checklist for author

- [x] `npm run lint` passes
- [x] References to standard library functions are [cached](https://github.com/sinonjs/sinon/pull/1523).

2024-01-04 18:01 UTC, Ethan-Arrowood approved these changes
Great work. Test case looks good to me. Appreciate you making this happen 🚀

2024-01-04 22:39 UTC, fatso83 requested changes
Thanks for having a go at this, @remorses! I tried taking a proper look, and I think I got there in the end, even though it was late. 

There are two main issues I need covered:
1. this needs to work for fakes, stubs and mocks as well
2. Optional context seems like a bad idea

Since stubs are spies that should be a wrap. I _guess_ mocks are covered by being proxies ... ? But AFAIK fakes do not share much code with these, so that needs to be addressed (I noted that in https://github.com/sinonjs/sinon/issues/2472#issuecomment-1612901648).

I am pretty sure you could template the test case so that you can make the same test for both spies and fakes, btw, just parameterising it by passing in some factory method.

Wrt the context, the fact that it has been made optional concerns me. Why is it optional? Is it just to avoid having to change testcases? A good IDE should be able to fill in default values for you when adding a new parameter. If it's just for convenience, I would rather just fix it. All spies are created from a sandbox, even the ones on the default Sinon instance, so there should be no need for the global module, AFAIK.

2024-01-04 22:39 UTC, fatso83 commented on test/sandbox-test.js
> +                }
This test was a bit hard to wrap my head around, at least at midnight ... 😄 Could you clarify what you are really doing? I mean, I assume you are somehow testing quazi-concurrent runs, interlacing runs from different sandboxes, but I still find it a bit hard to understand and read.

Is there some way you could re-order or refactor this in some way that made the intent as expressed through the code clearer? 

To me, it is not at all clear how the sandbox runs are being interlaced and in what order functions are being called. Would it not be much clearer if doing something a la this pseudo-code

```js
const sandboxASpy1 = sandboxA.spy();
const sandboxASpy2 = sandboxA.spy();
const sandboxBSpy1 = sandboxB.spy();
const sandboxBSpy2 = sandboxB.spy();

sandboxASpy1();
sandboxBSpy1();
sandboxBSpy2();
sandboxASpy2();

assert(sandboxASpy1.calledImmediatelyBefore(sandboxASpy2));
assert(sandboxBSpy1.calledImmediatelyBefore(sandboxBSpy2));
```

There is no need for awaits AFAIK. JS is single threaded no matter what, and the asynchronicity just muddles up what is going on IMHO.

2024-01-04 22:39 UTC, fatso83 commented on lib/sinon/sandbox.js
> +            sandbox,
If you are passing in the sandbox as the context, then what is the need for the global context object?

2024-01-04 22:39 UTC, fatso83 commented on lib/sinon/proxy.js
> +function wrapFunction(func, originalFunc, ctx = globalContext) {
Why are all of these context objects optional, with a default global? Even the default Sinon instance is a sandbox in itself.

2024-01-04 22:39 UTC, fatso83 commented on lib/sinon/proxy-invoke.js
> +    }
When does this ever happen? I cannot see any tests exercising this.

I see the fallback global module, where it is already initialised, and I see the sandbox, which is also initialised.

2024-01-04 22:39 UTC, fatso83 commented on lib/sinon/util/core/global-context.js
> +};
Is this even needed?

2024-01-04 22:51 UTC, fatso83 commented
This currently fails on your branch:
```javascript
✦ ❯ cat test/concurrency-test.js
const assert = require("node:assert");
const sinon = require("../lib/sinon");

const sbA = sinon.createSandbox();
const sbB = sinon.createSandbox();
const F = sbA.fake();

const f1 = sbB.fake();
const f2 = sbB.fake();

f1();
F();
f2();
assert(f1.calledImmediatelyBefore(f2));
```

2024-01-09 13:53 UTC, fatso83 commented
@remorses Do you need some guidance in how to progress? AFAIK the old-skool API is covered (haven't checked the mocks API, but I think that should be covered by the proxy stuff).

2024-01-25 11:32 UTC, fatso83 commented
Ping?

2024-02-15 11:32 UTC, fatso83 commented
This does not seem like it is going places. Closing due to unresponsiveness.

2024-02-15 11:32 UTC, closed without merging